# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 1800s
options:
  substitution_option: ALLOW_LOOSE
  machineType: 'N1_HIGHCPU_8'

steps:
- name: golang:1.22
  waitFor: ['-']
  env:
  - PULL_BASE_REF=$_PULL_BASE_REF
  - VERSION=$_GIT_TAG
  - DOCKER_REGISTRY=$_DOCKER_REGISTRY
  - DOCKER_IMAGE_PREFIX=$_DOCKER_IMAGE_PREFIX
  - ARTIFACT_LOCATION=$_ARTIFACT_LOCATION
  entrypoint: dev/staging/push-etcdadm.sh
- name: gcr.io/google.com/cloudsdktool/google-cloud-cli:slim
  waitFor: ['-']
  env:
  - PULL_BASE_REF=$_PULL_BASE_REF
  # We don't pass version; we want to use our own version tagging from git
  #- VERSION=$_GIT_TAG
  - DOCKER_REGISTRY=$_DOCKER_REGISTRY
  - DOCKER_IMAGE_PREFIX=$_DOCKER_IMAGE_PREFIX
  - ARTIFACT_LOCATION=$_ARTIFACT_LOCATION
  - INSTALL_BAZELISK=y
  entrypoint: dev/staging/push-etcdmanager.sh
substitutions:
  _GIT_TAG: 'dev'
  _PULL_BASE_REF: 'dev'
  _DOCKER_REGISTRY: 'gcr.io'
  _DOCKER_IMAGE_PREFIX: 'k8s-staging-etcdadm/'
  _ARTIFACT_LOCATION: 'gs://k8s-staging-etcdadm/ci/builds/'
